// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import (
	mock "github.com/stretchr/testify/mock"
	keyvalues "github.com/tokend/terraform-provider-tokend/tokend/connector/keyvalues"

	tx "github.com/tokend/terraform-provider-tokend/tokend/connector/tx"
)

// Connector is an autogenerated mock type for the Connector type
type Connector struct {
	mock.Mock
}

// KeyValues provides a mock function with given fields:
func (_m *Connector) KeyValues() keyvalues.KeyValues {
	ret := _m.Called()

	var r0 keyvalues.KeyValues
	if rf, ok := ret.Get(0).(func() keyvalues.KeyValues); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(keyvalues.KeyValues)
		}
	}

	return r0
}

// Submitter provides a mock function with given fields:
func (_m *Connector) Submitter() tx.HorizonSubmitter {
	ret := _m.Called()

	var r0 tx.HorizonSubmitter
	if rf, ok := ret.Get(0).(func() tx.HorizonSubmitter); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(tx.HorizonSubmitter)
		}
	}

	return r0
}
